# Generated by Django 5.1.4 on 2025-03-20 05:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_counselorleave_studentleave_delete_leaveapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselorleave',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studentleave',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
