# Generated by Django 5.1.4 on 2025-03-13 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('remarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remark',
            options={'ordering': ['-date_created'], 'verbose_name': 'Remark', 'verbose_name_plural': 'Remarks'},
        ),
        migrations.RemoveField(
            model_name='remark',
            name='staff',
        ),
        migrations.AddField(
            model_name='remark',
            name='counselor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='given_remarks', to='authentication.counselor'),
        ),
        migrations.AlterField(
            model_name='remark',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
