# Generated by Django 5.1.4 on 2025-03-16 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('remarks', '0002_alter_remark_options_remove_remark_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselorRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('percentage', models.FloatField()),
                ('remarks', models.TextField()),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.counselor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('remarks', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Remark',
        ),
    ]
