# Generated by Django 5.1.7 on 2025-03-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remarks', '0003_counselorremark_studentremark_delete_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselorremark',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='counselorremark',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
