databases:
  - name: majorprojectdb
    plan: free
    databaseName: majorproject
    user: majorproject

services:
  - type: web
    plan: free
    name: majorproject
    runtime: python3.10
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn majorproject.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: majorprojectdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4