# Generated by Django 5.1.4 on 2025-03-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_counselorwork_studentwork_delete_attendancereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselorwork',
            name='date',
            field=models.DateField(),
        ),
    ]
