# Generated by Django 5.1.4 on 2025-03-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_counselorwork_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counselorwork',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
