# Generated by Django 5.1.4 on 2025-03-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_counselorwork_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentwork',
            name='date',
            field=models.DateField(),
        ),
    ]
