# Generated by Django 5.1.4 on 2025-03-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='counselor',
            name='branch',
            field=models.CharField(choices=[('CIV', 'Civil Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('MEC', 'Mechanical Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('CSE', 'Computer Science Engineering'), ('INF', 'Information Technology'), ('CSM', 'Computer Science - AI & ML'), ('CSO', 'Computer Science - IoT'), ('CIC', 'Computer Science - Cybersecurity'), ('AIM', 'Artificial Intelligence and Machine Learning'), ('AID', 'Artificial Intelligence and Data Science')], max_length=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('CIV', 'Civil Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('MEC', 'Mechanical Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('CSE', 'Computer Science Engineering'), ('INF', 'Information Technology'), ('CSM', 'Computer Science - AI & ML'), ('CSO', 'Computer Science - IoT'), ('CIC', 'Computer Science - Cybersecurity'), ('AIM', 'Artificial Intelligence and Machine Learning'), ('AID', 'Artificial Intelligence and Data Science')], max_length=3),
        ),
    ]
