# Generated by Django 5.1.4 on 2025-03-12 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV')], null=True)),
                ('semester', models.IntegerField(blank=True, choices=[(1, 'I'), (2, 'II')], null=True)),
                ('working_days', models.IntegerField(default=0)),
                ('public_holidays', models.IntegerField(default=0)),
                ('present_percentage', models.FloatField(default=0.0)),
                ('absent_percentage', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_statistics', to='authentication.student')),
            ],
        ),
    ]
