# Generated by Django 5.1.4 on 2025-03-17 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_features', models.BinaryField(blank=True, null=True)),
                ('face_image', models.ImageField(blank=True, null=True, upload_to='face_images/')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
            ],
        ),
    ]
