# Generated by Django 5.1.4 on 2025-03-17 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_faceregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendance_percentage',
        ),
    ]
